[project]
name = "document-to-markdown"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markitdown[all]==0.1.2",
    "tqdm>=4.67.1",
]
